### ISSUE TITLE
有一个疑问,ChatGLM-Med为什么没有像华佗一样lora微调呢？

### ISSUE THREAD

**Issue by pogevip** [SCIR-HI/Huatuo-Llama-Med-Chinese#1]
是效果不好还是什么原因？

**Comment by thinksoso** [comment]
全量的话效果会更好一点。LLaMA用lora主要为了方便复现以及跟别的LLaMA-Based模型保持一致。

**Comment by pogevip** [comment]
> 全量的话效果会更好一点。LLaMA用lora主要为了方便复现以及跟别的LLaMA-Based模型保持一致。

好的，谢谢
