### ISSUE TITLE
请问这种输出乱码一般是什么原因呢？

### ISSUE THREAD

**Issue by herobrine19** [SCIR-HI/Huatuo-Llama-Med-Chinese#11]
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/45513138/233542749-2e473d90-bbff-4d0f-ab2a-874744aef7c6.png">

**Comment by s65b40** [comment]
您好，由于LLaMA的中文能力有限，其中文词表只有千个左右，部分回答中会存在一定概率的乱码，我们会在近期更新基于扩充词表的llama模型，会缓解上述问题，谢谢
