### ISSUE TITLE
与chatGLM-6B比较

### ISSUE THREAD

**Issue by hanswang73** [SCIR-HI/Huatuo-Llama-Med-Chinese#12]
https://chat.lmsys.org/   注意选择 chatGLM-6B
把主页的几个测试问题输入，好像没有微调过的 chatGLM-6B 的回答更好 .....

**Comment by KaishuaiXu** [comment]
我也发现了这个问题，好像原版回答更详细

**Comment by hanswang73** [comment]
所以，这个项目的价值是？

**Comment by SCIR-HI** [comment]
感谢您的关注，我们在项目初始时致力于以完全开源的角度尝试进行中大规模中文医学模型训练的尝试，当前chatGLM已经是中文对话模型中相当成熟的产品之一，我们希望逐渐探索开发中文医学模型的步骤，由于训练集数量和训练策略较为naive，我们期待通过不断的迭代为开源社区贡献一点点微薄之力，并一同实现效果更好的模型输出结果，再次感谢您的关注
