### ISSUE TITLE
是否有用到真实医疗场景数据？

### ISSUE THREAD

**Issue by KaishuaiXu** [SCIR-HI/Huatuo-Llama-Med-Chinese#14]
Hello！
想问下是否有用到其他数据集（除了instruct生成的数据外）？

**Comment by SCIR-HI** [comment]
您好，感谢您的关注，由于涉及真实场景的数据在医疗道德上存在一定的争议，我们先期以及当下并未采用真实的医疗数据，后续在去隐私化完成以及不违反相关法律法规的前提下，我们会尝试加入真实的医疗数据
