### ISSUE TITLE
数据集必须是instruct的形式吗？

### ISSUE THREAD

**Issue by dyabc1** [SCIR-HI/Huatuo-Llama-Med-Chinese#16]
肝癌疾病的中文医学文献，这个数据后面转换成了instruct的形式。想请问下，有没有可能不做转换？

**Comment by DYR1** [comment]
如果使用这套代码，只需要保持和我们提供的数据集格式一致即可，否则需要进一步修改代码

**Comment by dyabc1** [comment]
再目前代码前提下，保持跟目前数据集格式一致，这个可以理解。就是想请教下抛开目前的ft方法，有没有其他的形式将知识嵌入搞模型里面。

**Comment by DYR1** [comment]
最直观的方法应该就是尝试将“知识”融入对话中，让模型显示的去学习。但据目前实验来看，这种方式并不能够保证模型准确的学会细粒度的知识。目前，正在探究是否有其他方法能够更好的将“知识”融入大模型。

**Comment by dyabc1** [comment]
好的，感谢
