### ISSUE TITLE
About Huatuo

### ISSUE THREAD

**Issue by wabyking** [SCIR-HI/Huatuo-Llama-Med-Chinese#2]
Dear contributors,

Thanks for your insightful work and open-source project. I am happy to share our project  (https://github.com/FreedomIntelligence/LLMZoo) with you, which includes a tailored version of LLM in biomedince, and coincidently has the same name "Huatuo". The only difference is that we used different characters (驼or佗). Interestingly, we submitted a paper called "Huatuo" for ACL  2023 last December and meanwhile we have a website called https://www.huatuogpt.cn/ . Plus, we have registered related trademarks in Feb. 2023.  See an earlier news in http://www.sribd.cn/article/722  .

We do not intend to offend you but share some similar work with you. Hopefully, some win-win discussions could happend. If you not mind, maybe both names (华驼or华佗) could co-exist -- it might need some further discussions. 

Thanks for your project and we highly value the contributions in NLP from SCIR lab. Feel free to write to me via email or something else.

Best regards,
Benyou Wang
wangbenyou@cuhk.edu.cn
HuatuoGPT team.

**Comment by SCIR-HI** [comment]
Hi Benyou,

Thank you for getting in touch with us. It's quite a coincidence that we both have proposed a model named "HuaTuo". Our HuaTuo(华驼) was inspired by the naming convention of "Llama-Alpaca-....." which are all camelids (驼, Tuo). Therefore, 华驼 means 'Chinese (华) camelid (驼)' and is a play on words in the name of the Chinese ancient doctor, HuaTuo (华佗). Our 华驼(HuaTuo) model is an open-source project, which includes the base model, training data, training code, and tuned parameters. We will keep updating our model for better performance. Meanwhile, we have no commercial intentions with this project and would be happy to discuss further or collaborate with you. Please feel free to contact us via sdzhao@ir.hit.edu.cn if necessary.

Cheers,
SCIR-HI

**Comment by wabyking** [comment]
Thanks for your kind reply. Then it is totally fine.
