### ISSUE TITLE
询问一下，运行infer.py，报错TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yujianwei1** [SCIR-HI/Huatuo-Llama-Med-Chinese#20]
def main(
    load_8bit: bool = True,
    base_model: str = "decapoda-research/llama-7b-hf",
    # the infer data, if not exists, infer the default instructions in code
    instruct_dir: str = "./data/infer.json",
    use_lora: bool = True,
    lora_weights: str = "tloen/alpaca-lora-7b",
    # The prompt template to use, will default to med_template.
    prompt_template: str = "med_template",
):我的配置参数是这样的，其他的都和初始的一样，但我运行之后报错
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/bitsandbytes/autograd/_functions.py:3 │
│ 80 in forward                                                                │
│                                                                              │
│   377 │   │   │   if state.CxB is not None:                                  │
│   378 │   │   │   │   outliers = F.extract_outliers(state.CxB, state.SB, sta │
│   379 │   │   │   else:                                                      │
│ ❱ 380 │   │   │   │   outliers = state.CB[:, state.idx.long()].clone()       │
│   381 │   │   │                                                              │
│   382 │   │   │   state.subB = (outliers * state.SCB.view(-1, 1) / 127.0).t( │
│   383 │   │   │   CA[:, state.idx.long()] = 0                                │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1
我不知道为什么会这样，有人可以给我指导一下吗

**Comment by s65b40** [comment]
您好，请更新github仓库，如仍存在问题，请上传更完整的错误信息以便排查
