### ISSUE TITLE
请问如何利用GPT3.5生成医学文献多轮问答数据？

### ISSUE THREAD

**Issue by jimyang2008y** [SCIR-HI/Huatuo-Llama-Med-Chinese#21]
看到你们的项目中利用GPT3.5接口围绕医学文献多轮问答数据，我觉得这个idea很好。但是从示意图当中还是没太看明白具体是怎样生成多轮问答数据的。能再给出具体的解释吗？多谢！

**Comment by DYR1** [comment]
目前我们已经构造了一个围绕中文医学文献的多轮对话数据集（覆盖了肝胆胰相关的疾病），计划在本月中下旬以公开数据集的形式发布，欢迎关注！

**Comment by zlszhonglongshen** [comment]
会开源怎么利用chatgpt 接口进行的数据生成吗？

**Comment by cristianohello** [comment]
@DYR1 
你好，希望能开源怎么利用chatgpt 接口进行的多轮对话数据生成！谢谢

**Comment by Vebrun** [comment]
> 
您好，请问采用gpt3.5生成的对话数据集开放了吗？或者您提到的“围绕中文医学文献的多轮对话数据集”开放了吗？

**Comment by Vebrun** [comment]
@DYR1  您好，请问采用gpt3.5生成的对话数据集开放了吗？或者您提到的“围绕中文医学文献的多轮对话数据集”开放了吗？

**Comment by ihongxx** [comment]
@DYR1 你好，请问“围绕中文医学文献的多轮对话数据集”开放了吗？

**Comment by s65b40** [comment]
请大家稍等，我们会在相关研究工作完成后第一时间开放出来

**Comment by DumoeDss** [comment]
@s65b40 您好，请问“围绕中文医学文献的多轮对话数据集”开放了吗~

**Comment by liuyaox** [comment]
idea很赞！想请教，具体是如何利用GPT3.5和各种Prompt围绕中文医学文献生成多轮对话数据的，谢啦！

**Comment by DYR1** [comment]
@zlszhonglongshen @liuyaox @zlszhonglongshen @DumoeDss 
感谢大家对于基于中文医学文献生成对话数据的关注。
我们将最新的围绕医学文献的工作挂在了arxiv上 [https://arxiv.org/pdf/2309.04198.pdf](https://arxiv.org/pdf/2309.04198.pdf) ，基于医学文献构建的数据集，做了些分析性的实验，希望能给大家带来启发，欢迎大家关注！
此外，对于大家比较关心的如何基于医学文献构建SFT数据，我们在文章中提及了四个模块：1. Information Disassembly  2. Prompt Focus  3. Reverse Verification  4. Data Cleaning。
大家如果有任何疑问或者想法欢迎进一步交流！

**Comment by DumoeDss** [comment]
好耶

**Comment by s65b40** [comment]
感谢大家关注，如有疑问欢迎新开issue我们一起讨论
