### ISSUE TITLE
运行infer.sh文件出现错误

### ISSUE THREAD

**Issue by CodingPeasantzgl** [SCIR-HI/Huatuo-Llama-Med-Chinese#22]
运行infer.sh报错：没有找到adapter_config.json文件。
保存的权重文件如下：
<img width="150" alt="image" src="https://user-images.githubusercontent.com/49066765/236186586-a8fb7d68-7803-42ce-9c79-456af57ecf97.png">
请问是哪里出错导致没有adapter_config.json文件？

**Comment by yujianwei1** [comment]
你试试直接运行infer.py看看，我运行infer.py就没有这个错误

**Comment by CodingPeasantzgl** [comment]
感谢回复，问题已解决
