### ISSUE TITLE
有没有先进行预训练让llama拥有中文能力

### ISSUE THREAD

**Issue by yuanzhiyong1999** [SCIR-HI/Huatuo-Llama-Med-Chinese#23]
整个模型是直接在llama上面指令微调得来的吗？是不是先用中文语料让llama学习中文之后再指令微调会更好呢？

**Comment by s65b40** [comment]
您好，我们有更新基于中文Alpaca进行我们的指令微调，可参照我们的readme的更新日志

**Comment by yuanzhiyong1999** [comment]
我看了readme，但是代码里面都是基于llama或者alpaca的，请问发布的基于中文alpaca微调的是哪个版本的模型呢？7b 13b 还是plus版本？因为有很多细节问题，我想进一步了解一下，谢谢。

**Comment by s65b40** [comment]
是崔一鸣的alpaca-7B，readme上面有可以直接跳转的链接

**Comment by yuanzhiyong1999** [comment]
谢谢！
