### ISSUE TITLE
请问是否以经典中医医书为主？

### ISSUE THREAD

**Issue by jingrongx** [SCIR-HI/Huatuo-Llama-Med-Chinese#25]
包括但不限于易经，针灸大成，神农本草经，黄帝内经，黄帝外经，伤寒论，金匮要略？是否以经方为主，是否训练了名医书籍和医案？

**Comment by joostshao** [comment]
我反对中医，请去除中医语料库~

**Comment by lewislovelock** [comment]
为何要以中医医书为主，中医诊断还是去现场看中医为好～

**Comment by duaneya** [comment]
> 为何要以中医医书为主，中医诊断还是去现场看中医为好～

不以中医医书为主干嘛叫华佗啊

**Comment by pangwenfeng** [comment]
> > 为何要以中医医书为主，中医诊断还是去现场看中医为好～
> 
> 不以中医医书为主干嘛叫华佗啊

Q&A不是说了没有使用中医医书的数据了吗？
