### ISSUE TITLE
申请入群

### ISSUE THREAD

**Issue by herove** [SCIR-HI/Huatuo-Llama-Med-Chinese#27]
请问如何加群，群显示超过200人需要邀请，下面的个人码显示被加太多，被腾讯风控了

**Comment by lp380490944** [comment]
一样的情况

**Comment by developerworks** [comment]
![image](https://user-images.githubusercontent.com/725190/236736025-f5506503-f121-43bc-987a-455559bd5250.png)

**Comment by moonfansLTH** [comment]
求拉群，vx：13521879958

**Comment by SunLemuria** [comment]
+1

**Comment by thisiskeithkwan** [comment]
求拉群， wx: thisiskeithkwan

**Comment by SupritYoung** [comment]
求拉群，wx:SupritYoung

**Comment by York1111** [comment]
求拉群，wx: syg1111

**Comment by yixian3500** [comment]
求拉群，wx:15512641769

**Comment by cxj121** [comment]
求拉群，wx:15556932820

**Comment by tangjinou** [comment]
求拉群，wx:18605811551

**Comment by zj2050** [comment]
求拉群，wx:tb1901324058  谢谢

**Comment by David-19940718** [comment]
求拉群，wx:ww10874

**Comment by tangjinou** [comment]
求拉群，vx：18605811551

**Comment by BUAA-Worromot** [comment]
求拉群，vx：Worromots

**Comment by LEOMessi6** [comment]
求拉群，VX：LEOMessiCurry

**Comment by twi1ight00** [comment]
求拉群， wx: Iamfine3qandu666

**Comment by SunLemuria** [comment]
求拉群，vx：Wilson-mz

**Comment by xxAkuya** [comment]
求拉群 V:oofyJOKER

**Comment by Forever-Young-l** [comment]
求拉群，wx：wxid_pn6suytaiwbz22

**Comment by jia110** [comment]
求拉群，wx：God-9168
