### ISSUE TITLE
是不是可以用Text generation web UI来部署

### ISSUE THREAD

**Issue by yixian3500** [SCIR-HI/Huatuo-Llama-Med-Chinese#28]
如果可以的话，基础模型是Alpaca-7B 还是Chinese-Alpaca-7B
Lora用华驼这个项目的模型？

**Comment by s65b40** [comment]
可以的，是cuiyiming的Chinese-Alpaca-7B，lora用项目里的就可以

**Comment by yixian3500** [comment]
感谢回复
