### ISSUE TITLE
eval_loss为nan是什么原因

### ISSUE THREAD

**Issue by yuanzhiyong1999** [SCIR-HI/Huatuo-Llama-Med-Chinese#29]
![image](https://user-images.githubusercontent.com/94682439/236980265-c14e6e26-6459-4db1-a672-2bf80cd0d6e3.png)
如上图
训练过程中eval_loss为nan，参数我只修改了 batch，别的都保持一致
请问这是什么原因？

**Comment by yyanhan** [comment]
我也在其他项目里遇到了同样的问题，我猜测可能是huggingface或者什么的问题，但是还不确定
