### ISSUE TITLE
百度网盘密码错了啊

### ISSUE THREAD

**Issue by ScienGU** [SCIR-HI/Huatuo-Llama-Med-Chinese#32]
百度网盘密码错了啊

**Comment by s65b40** [comment]
您好，刚刚我们检查了一遍，没有发现错误，请问是哪个链接存在问题

**Comment by mellivoraPKU** [comment]
> 您好，刚刚我们检查了一遍，没有发现错误，请问是哪个链接存在问题

对Alpaca进行指令微调的LoRA权重文件
基于医学知识库 [百度网盘](https://pan.baidu.com/s/16oxcjzXnXjDpL8SKihgNxw?pwd=scir)

**Comment by mellivoraPKU** [comment]
@s65b40

**Comment by ScienGU** [comment]
> 您好，刚刚我们检查了一遍，没有发现错误，请问是哪个链接存在问题

抱歉，在电脑上直接点击跳转会密码错误，复制链接到百度网盘就没问题了
