### ISSUE TITLE
你好，感谢开源！希望能开源怎么利用chatgpt 接口进行的多轮对话数据生成！谢谢

### ISSUE THREAD

**Issue by cristianohello** [SCIR-HI/Huatuo-Llama-Med-Chinese#33]

**Comment by philipyao** [comment]
同求。能不能简单介绍一下思路。

**Comment by SupritYoung** [comment]
同问，非常好奇

**Comment by oneTaken** [comment]
可以参考下[self-instruct](https://github.com/yizhongw/self-instruct) ，与[Chinese-LLaMA-Alpaca](https://github.com/ymcui/Chinese-LLaMA-Alpaca) 这两个repo，核心思想是一样的
