### ISSUE TITLE
chinese-alpaca使用的模板与华驼不一致

### ISSUE THREAD

**Issue by yuanzhiyong1999** [SCIR-HI/Huatuo-Llama-Med-Chinese#34]
chinese-alpaca使用原版stanford-alpaca不带input的模板，是英文的，华驼使用中文的模板在chinese-alpaca的基础上继续指令精调，这样的话，他们模板不一致，会不会产生很大的gap呢？

**Comment by rootnx** [comment]
感谢对本草（原华驼）的关注~

精调的目的就是为了弥合这个gap，以适用我们希望的场景
