### ISSUE TITLE
请问如何基于中文Alpaca大模型进行指令微调？

### ISSUE THREAD

**Issue by SupritYoung** [SCIR-HI/Huatuo-Llama-Med-Chinese#38]
我观察到作者在README 中提到了目前已支持 中文Alpaca大模型。但其也是一个 lora 权重，如何在模型里加载两份 lora 权重呢？

**Comment by oneTaken** [comment]
一份lora 权重 + 基础的模型就是一个完整的模型。
两份lora 权重就是两个大模型，互斥的。

**Comment by s65b40** [comment]
您好，lora是可以叠加的，llama+中文alpaca lora可以合并为一个模型，之后可以和我们训练的lora进行叠加

**Comment by jzssz** [comment]
> 您好，lora是可以叠加的，llama+中文alpaca lora可以合并为一个模型，之后可以和我们训练的lora进行叠加

请问如何将llama与您训练的lora叠加？（或者llama+中文alpaca lora合并为一个模型之后，如何再和您训练的lora进行叠加？）感谢！！！
