### ISSUE TITLE
我觉得“华驼”这个名字更好

### ISSUE THREAD

**Issue by devinzhang91** [SCIR-HI/Huatuo-Llama-Med-Chinese#39]
RT

**Comment by shenjler** [comment]
哈哈，我也觉得是。毕竟国外的是羊驼，国内叫华驼没毛病

**Comment by ayaka14732** [comment]
华驼谐音华佗，华佗是中国古代名医；同时 LLaMA 是羊驼，在中文数据集上微调之后是中华的羊驼，简称华驼。本草是中国古代著名医书的名字，象征着模型在微调过程中遍览医书，是医学知识的宝库；同时 LLaMA 又称草泥马，基于 LLaMA 微调的模型本来是草泥马，所以简称本草。我觉得两个名字都非常巧妙。

**Comment by rootnx** [comment]
感谢对本草（原华驼）的关注~

为SCIR实验室大语言模型命名一致性，中文医学大模型名称调整为"本草"
