### ISSUE TITLE
关于训练数据的生成

### ISSUE THREAD

**Issue by ShawnChang-ei** [SCIR-HI/Huatuo-Llama-Med-Chinese#4]
您好，想请教以下问题：
1、知识库中的单条数据用于生成几条训练数据？训练数据生成后采用了什么筛选策略呢？如何判断知识库中的信息被正确利用了？
2、med_template.json里的prompt仅用于推理阶段吗？
不胜感激！

**Comment by thinksoso** [comment]
1. 一条知识生成的训练数据应该是越多越好，受限于GPT3.5接口的长度限制，我们设定为一次性生成五条，实际上对重点的疾病需要多次生成保证质量。仓库中公开的数据集暂时没有进行验真，我们通过生成时的提示尽可能确保GPT3.5利用提供的知识来生成数据。目前版本还不完善，我们在做更多的工作，感谢关注!
2. 训练和推理的prompt保持了一致
