### ISSUE TITLE
如何复现基于Chinese-alpaca-7b的医学知识和医学文献对话模型?

### ISSUE THREAD

**Issue by LouisHeck** [SCIR-HI/Huatuo-Llama-Med-Chinese#44]
在本地测了Chinese-alpaca-7b + lora-alpaca-med-alldata，在多轮对话上，效果很好。

请问：
1. 如何利用llama.json以及liver_cancer.json，如何合并数据集（一个多轮对话，一个单轮对话），直接合并放在一个文件么？
2. 复现您们的训练效果，该使用哪个模板？('med_template' or 'literature_template.json')
3. 目前我有 8 X A100(40G)， micro_batch_size和batch_size该如何设置（都是64么？为您们设置的一半？）
4. 关于LoRA的rank和alpha值？听说在垂直领域微调时，加大LoRA的rank值效果会好些，想问下您们关于LoRA的rank值以及alpha值的选取的相关经验

感谢您们百忙之中抽空解答，祝项目越来越好，感谢！

**Comment by rootnx** [comment]
感谢对本草（原华驼）项目的关注，针对您提出的问题：
1. 两个json文件并无关系，不应合并
2. 模板取决于要用哪个任务，请结合具体任务选择相应的模板
3. 我们训练时使用的是单卡80g A100，具体设置可以自己试一下，不同硬件及模型部署会有差异
4. 我们并未对LoRA的rank/alpha做不同配置，最大的问题是生成结果很难评价，整体上看一些超参变了之后结果是有好有坏
