### ISSUE TITLE
训练数据集的构建

### ISSUE THREAD

**Issue by yungangwu** [SCIR-HI/Huatuo-Llama-Med-Chinese#45]
请问你们是如何利用GPT3.5的api加本地已有的数据，来构建的训练数据集呢？

**Comment by yungangwu** [comment]
@Tamiflu233  我的理解是向gpt输入文本，让其利用这段文本构建问题，但是按照我在glm的试验，一是它不能很好的将一段文本转化问题，二是返回的内容通常并不纯粹的是要求返回的问题，而是包括分析内容。所以这个项目中对于数据集的构建过程，对我而言是比较看重的~或者有什么其他好的实现方法，也可以交流一下

**Comment by BUAA-Worromot** [comment]
同问

**Comment by hzwy3c** [comment]
同问

**Comment by Forever-Young-l** [comment]
1

**Comment by zjhJOJO** [comment]
同问

**Comment by s65b40** [comment]
欢迎大家查看我们最新的论文，其中有更加详细的描述
