### ISSUE TITLE
训练后的数据不理想

### ISSUE THREAD

**Issue by frog-game** [SCIR-HI/Huatuo-Llama-Med-Chinese#47]
**`这是我改过的infer-literature-single.sh脚本内容`**
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/31720616/738510e2-36e1-454f-b52e-1f159df0663c)

**`这是我调用bash ./scripts/finetune.sh执行的finetune脚本`**
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/31720616/cb49e245-316d-49d2-8871-af8e44f63082)

**`这是结果`**
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/31720616/eed7d691-ae67-400e-95b1-641610e682a2)

**Comment by s65b40** [comment]
您好，感谢您的关注，您运行的脚本是基于文献生成数据的指令微调训练过程，由于一些原因，我们当前开源的文献生成数据仅为样例，并非全部的数据，故训练出的模型效果有限，如有需要，您可以收集一些文献，构造一批指令微调数据，这样的效果会更好些，谢谢

**Comment by herobrine19** [comment]
<img width="896" alt="image" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/45513138/e461be3c-0269-498e-9590-cf10ebd807e6">
请问这种情况 是因为数据太少了导致的吗

**Comment by woshicqy** [comment]
你好，请问你是什么操作系统，如何本地部署的啊？我目前本地部署，bitsandbytes总是报错

**Comment by s65b40** [comment]
> 的

复读的问题在基于LLaMA指令微调的背景下是很常见的问题，原因也是多样的，根据经验可以通过对模型扩充中文词表，增加训练数据，超参设置等进行缓解
