### ISSUE TITLE
代码的问题

### ISSUE THREAD

**Issue by wuguangshuo** [SCIR-HI/Huatuo-Llama-Med-Chinese#51]
在多轮对话infei时会出现大量的#号，这是为什么

<user>: 小张最近感觉身体不适，出现心悸、气促等症状。体检发现心脏扩大、搏动减弱。 <bot>: 我建议您及家人及您的医生进行进一步的检查，以确定小张的病因。同时，我建让您及家人做好的饮食和生活习惯，以避免其他的健康问题。###########################################################################################################################<user>: 小王被确诊为肝炎双重感染，最可能的并发症是什么？ <bot>: 根据相关文献，肝炎双重感染的危险因素主要包括肝炎、营养不良、免疫抑制剂、病毒敏感免疫等。因此，我建让您及家人及您的医生进行进一步的检查，以确定小张的病因。

**Comment by woshicqy** [comment]
请问一下，你在本地成功部署了么？为什么我一直会cuda报错啊？ #48

**Comment by s65b40** [comment]
这个#应该是代码中人工设置的分隔符，如果不喜欢可以去掉或者替换成别的符号
