### ISSUE TITLE
为什么使用提供的alpaca 的lora参数推理出来的结果完全不对，胡言乱语

### ISSUE THREAD

**Issue by HeisenbergSu** [SCIR-HI/Huatuo-Llama-Med-Chinese#52]
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/52101859/c69e7aa7-7c87-4a77-bf22-b91e9d5df1aa)

**Comment by YaxinCui** [comment]
<img width="1013" alt="截屏2023-05-25 16 38 16" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/30173253/e30888a8-29c0-4037-8465-3902fea26b5e">

我的推理结果也不对，基于llama。
具体参数如下：
    base_model: str = "decapoda-research/llama-7b-hf",
    # the infer data, if not exists, infer the default instructions in code
    instruct_dir: str = "",
    use_lora: bool = True,
    lora_weights: str = "lora-llama-literature",

**Comment by chenxu126** [comment]
我的也是，请问我问题解决了没？

**Comment by s65b40** [comment]
您好，请描述一下您的设置，我们尝试复现一下

**Comment by Nisoka** [comment]
是需要先将 chinese-llama-alpaca 的模型组合之后 作为 base_model么，还是直接用原来的 LLaMa(META) 的？

**Comment by s65b40** [comment]
> 是需要先将 chinese-llama-alpaca 的模型组合之后 作为 base_model么，还是直接用原来的 LLaMa(META) 的？

您好，都可以的，我们提供了针对原始的llama以及中文alpaca的lora模型参数
