### ISSUE TITLE
“结论”信息如何融入多轮对话中

### ISSUE THREAD

**Issue by toughhou** [SCIR-HI/Huatuo-Llama-Med-Chinese#56]
“利用GPT3.5 API将医学文献中的【结论】作为外部信息融入多轮对话中，在此基础上对LLaMA进行了指令微调”

请问具体是怎么做的呢？是否能详细介绍一下？“结论”信息如何融入多轮对话中？

**Comment by toughhou** [comment]
Knew it now.

**Comment by s65b40** [comment]
@DYR1

**Comment by DYR1** [comment]
最近正在写论文，目前在做一些实验，会介绍一套完整的训练、测试流程。会介绍如何融入结论信息，并且会定量的评测信息融入是否成功。论文计划会先挂在arxiv上，可以再稍微等一下~
