### ISSUE TITLE
模型效果评测

### ISSUE THREAD

**Issue by toughhou** [SCIR-HI/Huatuo-Llama-Med-Chinese#57]
请问是否对BenTsao做过领域能力与通用能力的评测？
模型训练只是使用了8K+的医疗领域指令微调吗？如果这样的话模型会灾难遗忘吧，忘记通用的一些能力。

**Comment by Forever-Young-l** [comment]
+1

**Comment by chenxu126** [comment]
+1

**Comment by s65b40** [comment]
您好，我们当前没有做通用能力评价。目前开源的是8k的指令微调数据以及一部分基于文献的问答数据。是存在忘记通用域的能力的情况的，这种情况可以通过构建包含通用域数据、持续学习等方式缓解。
