### ISSUE TITLE
med模板 prompt input  与 noinput 模板都不包含input, 是不是写错了？ 

### ISSUE THREAD

**Issue by liangsh0208** [SCIR-HI/Huatuo-Llama-Med-Chinese#58]
{
    "description": "Template used by Med Instruction Tuning",
    "prompt_input": "下面是一个问题，运用医学知识来正确回答提问.\n### 问题:\n{instruction}\n### 回答:\n",
    "prompt_no_input": "下面是一个问题，运用医学知识来正确回答提问.\n### 问题:\n{instruction}\n### 回答:\n",
    "response_split": "### 回答:"
}

**Comment by s65b40** [comment]
您好，没有包含input是因为我们的训练集中只有instruction而没有input，我们认为医学问答中instruction存在的必要性有限，进而将input作为instruction，input则为空。如果在您的项目需求中同时需要instruction和input，可以在构造数据集之后，将{input}添加到模板之中。
