### ISSUE TITLE
项目提供的lora没有达到提的效果呀，就给的那几个infer的例子

### ISSUE THREAD

**Issue by Zombiessss** [SCIR-HI/Huatuo-Llama-Med-Chinese#6]
![image](https://user-images.githubusercontent.com/25706482/233026796-6b5e2b9d-98ce-479c-9b6b-50f9f538fe17.png)

**Comment by SCIR-HI** [comment]
您好，感谢您的关注，目前由于beam search等设置，模型对于相同输入的回答每次可能不尽相同，您可以尝试多次运行。此外，由于当前模型训练集大小有限，模型在微调后能力也因此受限，目前我们正在进行更大规模、质量更优的数据收集，以及训练方法上的更新，很快将进行模型的迭代。

**Comment by Zombiessss** [comment]
> 

跟beam search没啥关系吧，这效果差的很远啊，那个golden output是真的inference出来的效果吗，如果是的话可以把那个lora的ckpt release下吗

**Comment by Chengzhe-Feng** [comment]
我使用提供的lora也得到了类似的结果 请问infer.py中关于temperature等参数的设置与您当时跑示例时一致么
![huatuo](https://user-images.githubusercontent.com/51310707/233826406-2d6a5845-e21b-4f3c-b150-74ab9f97f62b.png)

**Comment by Gavingx** [comment]
同样的问题。感觉效果跟作者贴出来的图片上的效果差挺多的，试了各种超参的组合，结果好像没什么改变。base_model是llama-7b-hf，lora是作者开放出来的[https://huggingface.co/thinksoso/lora-llama-med](https://huggingface.co/thinksoso/lora-llama-med)。
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/43789460/13dede74-ce10-484f-83a0-959753247313)

**Comment by zhengorange** [comment]
作者您好，我这里也是出现了同样的问题，是不是您那边放错了lora文件
<img width="1035" alt="截屏2023-05-28 00 27 37" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/51870856/7bc8f064-7433-4eb9-9d86-00b236b5f23f">

**Comment by leslielu248gmail** [comment]
base用baffo32/decapoda-research-llama-7B-hf可以达到效果，但是没懂为什么不用官方的llama模型
