### ISSUE TITLE
发现好多人提了很多问题，项目上的人回复的很少，这个项目是不是用来炒作的？

### ISSUE THREAD

**Issue by chenxu126** [SCIR-HI/Huatuo-Llama-Med-Chinese#61]

**Comment by rootnx** [comment]
感谢对本草（原华驼）的关注~

本项目为纯公益非盈利开源项目，我们的团队规模相对较小，人力资源有限，同时也有其他科研工作需要推进，且许多需要debug的issue比较个人化也难以复现，无法及时回复。感谢大家的理解和支持。
