### ISSUE TITLE
RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'Half'

### ISSUE THREAD

**Issue by liulj0507** [SCIR-HI/Huatuo-Llama-Med-Chinese#66]
<img width="1128" alt="image" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/21101729/f369d7f4-c7fc-4257-9a05-92e2cc9c566f">

运行infer.sh的时候遇到上面错误，怎么解啊？

**Comment by s65b40** [comment]
您好，请确保依赖包的版本号和requirements中一致，如仍有问题，请详细描述使用场景以便排查
