### ISSUE TITLE
请问推理需要占用多少显存，我40GB运行infer.sh提示：CUDA error: out of memory

### ISSUE THREAD

**Issue by Macvh** [SCIR-HI/Huatuo-Llama-Med-Chinese#69]
python3.8 infer.py \
    --base_model './llama-7b-hf' \
    --lora_weights './lora-llama-med' \
    --use_lora True \
    --instruct_dir './data/infer.json' \
    --prompt_template 'med_template'
    
    
 在using lora的时候报错
 
<img width="638" alt="image" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/45690047/5d599ba5-67d6-46be-920a-7423579b902e">

**Comment by Macvh** [comment]
不知道是不是和bitsandbytes有关
<img width="983" alt="image" src="https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/45690047/684ade00-ca30-496f-b443-e5f737f8c31d">

**Comment by s65b40** [comment]
单纯推理40GB应该是够用的，报错内容不是很完整，但看起来是cuda环境问题，请确定cuda环境已添加至环境变量且版本匹配

**Comment by 200109110057Wjy** [comment]
请问你解决了吗，我也遇到同样的问题
