### ISSUE TITLE
An error occurred while generating the dataset

### ISSUE THREAD

**Issue by chencoder1** [SCIR-HI/Huatuo-Llama-Med-Chinese#71]
raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset  当我的训练数据超过两万条左右时就会出现这个错误，有没有遇到这种情况的？

**Comment by s65b40** [comment]
我们也有在更大规模数据上进行训练，没有出现过类似错误，可以考虑一下数据集的格式是否存在问题

**Comment by zhu-code** [comment]
请问llama_data.json这个文件就用cmedkg构建的数据吗
