### ISSUE TITLE
我设置了cuda:0，但是还是显示Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

### ISSUE THREAD

**Issue by handsomexiaoyi** [SCIR-HI/Huatuo-Llama-Med-Chinese#73]
在运行infer.sh文件时，遇到了错误
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/129043313/8a19a91c-8c6d-42cd-8a3a-f22b5656c82e)

**Comment by s65b40** [comment]
你好，建议尝试设置cuda环境，只让cuda0可见，应该可以解决这个问题

**Comment by gggdroa** [comment]
> 你好，建议尝试设置cuda环境，只让cuda0可见，应该可以解决这个问题

我创建了cuda环境  指定到0  还是会报这样的错误

**Comment by gggdroa** [comment]
> 在运行 infer.sh 文件时，遇到了错误 ![图像](https://user-images.githubusercontent.com/129043313/252948171-8a19a91c-8c6d-42cd-8a3a-f22b5656c82e.png)

请问您解决了吗

**Comment by handsomexiaoyi** [comment]
> > 在运行 infer.sh 文件时，遇到了错误 ![图像](https://user-images.githubusercontent.com/129043313/252948171-8a19a91c-8c6d-42cd-8a3a-f22b5656c82e.png)
> 
> 请问您解决了
我在命令行加了一句，CUDA_VISIBLE_DEVICES='0' bash ./scripts/infer-literature-multi.sh

**Comment by gggdroa** [comment]
> > > 在运行 infer.sh 文件时，遇到了错误 ![图像](https://user-images.githubusercontent.com/129043313/252948171-8a19a91c-8c6d-42cd-8a3a-f22b5656c82e.png)
> > 
> > 
> > 请问您解决了
> > 我在命令行加了一句，CUDA_VISIBLE_DEVICES='0' bash ./scripts/infer-literature-multi.sh

感谢回复
