### ISSUE TITLE
答非所问

### ISSUE THREAD

**Issue by gggdroa** [SCIR-HI/Huatuo-Llama-Med-Chinese#76]
这是什么情况呢？试了很多次，不是重复就是卡住？是我用错模型或指定错文件了吗
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/106646583/f89c324b-fdd4-49de-b5d2-e50514636782)

**Comment by aaadrain** [comment]
这个template是怎么用呀？我如果要微调其他的任务，我该如何修改？

>

**Comment by s65b40** [comment]
template可以视为一种提示序列，如想在其他任务上微调，请确保训练和测试时使用了同样的template，如果问题可以在新开issue一起讨论
