### ISSUE TITLE
如何使用微调后的模型

### ISSUE THREAD

**Issue by handsomexiaoyi** [SCIR-HI/Huatuo-Llama-Med-Chinese#77]
只用修改微调后的权重去做预测吗？
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/129043313/e7fbc60f-ee7c-4097-b56f-1f376682a1b5)

**Comment by s65b40** [comment]
您好，我们采用的事lora微调的方法，微调时同时利用基模型base model和lora权重lora weights
