### ISSUE TITLE
与技术无关，单纯的好奇，为什么是“驼“而不是“佗”？

### ISSUE THREAD

**Issue by haozhi1817** [SCIR-HI/Huatuo-Llama-Med-Chinese#8]
冒昧问一下。

**Comment by SCIR-HI** [comment]
hhhh 感谢您的关注，叫”驼“是因为llama是美洲驼，alpaca是羊驼，受他们名字的启发以及华佗的谐音梗，我们起名为华驼，由于名字不太严肃，以及后来有同期更早的工作起名为了华佗，我们未来的模型更新将会命名为”扁鹊“。

**Comment by haozhi1817** [comment]
> hhhh 感谢您的关注，叫”驼“是因为llama是美洲驼，alpaca是羊驼，受他们名字的启发以及华佗的谐音梗，我们起名为华驼，由于名字不太严肃，以及后来有同期更早的工作起名为了华佗，我们未来的模型更新将会命名为”扁鹊“。

哈哈哈，非常感谢您的认真回复。
