### ISSUE TITLE
希望取得联系

### ISSUE THREAD

**Issue by JimmyMa99** [SCIR-HI/Huatuo-Llama-Med-Chinese#83]
尊敬的Huatuo-Llama-Med-Chinese应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现Huatuo-Llama-Med-Chinese的可能性和实现路径，我的微信是mzm312，希望可以取得联系进行更深度的交流

**Comment by s65b40** [comment]
您好，相关合作请和赵森栋老师联系，谢谢，sdzhao@ir.hit.edu.cn
