### ISSUE TITLE
您好，您这个项目如何运行起来？

### ISSUE THREAD

**Issue by endluo** [SCIR-HI/Huatuo-Llama-Med-Chinese#84]
我按照教程配置了python3.9和安装了requirements.txt里面的库，直接在pycharm运行infer.py的时候报错了，报错信息如下
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/26343370/cb392e30-9e07-40c5-b262-be6e4d8b5474)
对了：
1、我没有GPU环境，是否能运行infer.py
2、我把模型文件都复制到主目录下
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/26343370/e9a69498-ba8f-4444-a287-6110fde30e51)
3、代码也改成如下
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/26343370/f1bf1a7f-b97e-4f3c-b797-3ffadbeb0665)
请问是什么原因？

**Comment by endluo** [comment]
![image](https://github.com/SCIR-HI/Huatuo-Llama-Med-Chinese/assets/26343370/b2f06e4b-78f8-4cb5-ada8-6a31dab8554e)
换到服务器上了，又报了这个错

**Comment by s65b40** [comment]
您好，本项目当前需要显存足够大的GPU才可以运行，您最后截图中的错误应该是cuda路径的问题，需要确定cuda已安装并已添加至环境变量

**Comment by endluo** [comment]
好的呢，thx
