### ISSUE TITLE
指令微调的训练集的数据分布

### ISSUE THREAD

**Issue by zhangyu68** [SCIR-HI/Huatuo-Llama-Med-Chinese#85]
请问训练集中只包含医疗领域的数据吗，还是融入了一定比例的通用数据

**Comment by s65b40** [comment]
您好，我们只包含了医疗领域数据，因此会存在通用能力的下降，如您有需要，可以进行通用数据的融入

**Comment by zhu-code** [comment]
请问llama_data.json这个文件就用cmedkg构建的数据吗
