### ISSUE TITLE
How to finetune on huozi?

### ISSUE THREAD

**Issue by Holly-Max** [SCIR-HI/Huatuo-Llama-Med-Chinese#91]
Since you guys have updated the finetune model of huozi. I wonder if I want to finetune on huozi using my own data. Should I modified the finetune.py script?

**Comment by s65b40** [comment]
Hi, yes. If you wanna fine-tune Huozi with your own data, please mod the finetune.sh file with 'Huozi' base model, your own data, and the prosper prompt template (and other parameters if necessary).

**Comment by Holly-Max** [comment]
Thanks!
